### ISSUE TITLE
Please Can you implement mqtt client?

### ISSUE THREAD

**Issue by uronito** [sstadlberger/botvac-wifi#3]
This project is wonderful!!!!

Please Can you implement mqtt client?

Thanks in advance.

Regards

**Comment by sstadlberger** [comment]
I'm sorry but I don't know anything about about MQTT and sadly my time is somewhat limited. But you are very welcome to contribute.

**Comment by uronito** [comment]
One question please.

If i use esp8266-01 , must connect ch_pd,rest pins to vcc?

Thanks!!!

**Comment by sstadlberger** [comment]
CH_PD and REST should be pulled to 3.3V, ideally via a 1k resistor.

Please see the ESP8266 Community wiki for more information on getting started:
http://www.esp8266.com/wiki/doku.php?id=getting-started-with-the-esp8266

There is also a forum where you can ask general ES8266 questions:
http://www.esp8266.com/
