### ISSUE TITLE
What connector did you use?

### ISSUE THREAD

**Issue by craftyguy** [sstadlberger/botvac-wifi#4]
>  I used Dupont connectors.

Do you have a link to it on digikey or elsewhere?

**Comment by sstadlberger** [comment]
For example: https://www.aliexpress.com/item/o/32801013353.html

I just used them to be able to disconnect the cable. The cable itself is soldered to the board because I couldn't find a proper connector. Please share if you find one.

**Comment by craftyguy** [comment]
Oh, ok, I see. I thought you found a proper connector to connect directly to the board, I didn't know what a 'dupont connector' was until now. I have ultimately done the same thing you did, soldered wires directly to board, with a similar style connector at the other end. Sorry for the frivolous issue 'ticket', it was the only way I could ask you this question!
