### ISSUE TITLE
Connector on Vorwerk VR100

### ISSUE THREAD

**Issue by dewi-ny-je** [sstadlberger/botvac-wifi#7]
This is not an issue, more a support request.

Are you aware of similar connectors on the Vorwerk VR100? it's based on the Neato, with minor mechanical and battery changes. The display even shows "Neato".

When I opened it I couldn't find anything clearly labeled as "TX, RX".

**Comment by sstadlbergerxamine** [comment]
Sorry, I'm aware that the Vorwerk vacuums are based on Neato (they even bought Neato last year), but I've never been able to examine one.

If you have an oscilloscope with a serial decoder you might be able to probe the board and find the proper connections. I don't have any further ideas.

**Comment by sstadlberger** [comment]
Sorry, I'm aware that the Vorwerk vacuums are based on Neato (they even bought Neato last year), but I've never been able to examine one.

If you have an oscilloscope with a serial decoder you might be able to probe the board and find the proper connections. I don't have any further ideas.

**Comment by berti92** [comment]
It works on VR100 I own myself, too. But keep in mind that there are a few revisions which don't support Serial.
