### ISSUE TITLE
bot stops current programm at disconnect

### ISSUE THREAD

**Issue by AnduriI** [sstadlberger/botvac-wifi#8]
Hey there,

I modded my D85 with an ESP and it works. I can read the status and query it from my home automation system.
Only problem happens when I query the status during operation of the robot. It than says navigation not possible (I think it was error code 2000) (not shure about the exact words, my robot is set to german).
This also happens when I go to the webpage and issue a "clean" command: it will start and after a few minutes it will stop with that message. I think that's the time when my http connection gets a timeout and some kind of disconnect is send.

Hope anyone knows how to fix this.

Regards,
Anduril

**Comment by sstadlberger** [comment]
The disconnect should not affect the operation of the bot. When disconnecting from the websocket, a "TestMode off" command is send to the bot as a precaution, but that should only affect the bot if the testmode is enabled (which it should not be for normal operations).

Other then that I can only suggest the obvious troubleshooting steps like checking connections and if possible to sniff the serial data between then ESP and the bot.

I'm sorry that I cannot be of more help, maybe someone else has a good idea.

**Comment by AnduriI** [comment]
well I reuploaded the sketch without the "TestMode off" at disconnect and it runs fine for a few days. If anyone else has this kind of problem you could maybe try, but I do not recommend using this long term (or at all if you use TestMode).
